### ISSUE TITLE
Estabelecer ligações entre as páginas 

### ISSUE THREAD

**Issue by crisper2001** [MathiasBelmont/memo-io-front#1]
- [x] Instalar o React Router no projeto via NPM
- [x] Configurar o React Router (incluir o RouterProvider em main.tsx)
- [x] Definir as rotas de cada página
- [x] Ligar a página de login à página de cadastro e vice-versa
- [x] Ligar a página de login e a página de cadastro à página principal
- [x] Ligar a página principal à página de login por meio de um botão de log off

[Tutorial](https://reactrouter.com/en/main/start/tutorial)

**Comment by MathiasBelmont** [comment]
> * [x]  Instalar o React Router no projeto via NPM
> * [x]  Configurar o React Router (incluir o RouterProvider em main.tsx)
> * [x]  Definir as rotas de cada página
> * [x]  Ligar a página de login à página de cadastro e vice-versa
> * [x]  Ligar a página de login e a página de cadastro à página principal
> * [x]  Ligar a página principal à página de login por meio de um botão de log off
> 
> [Tutorial](https://reactrouter.com/en/main/start/tutorial)

Realizado as tarefas commit será realizado na branch matheus
